from UI import App
from data_processing import load_data, load_and_preprocess_data
from encoders import OneHotEncoder
from logic import run_main_logic
# Main logic:
if __name__ == "__main__":
    # encoder = OneHotEncoder()
    # print("Aju")
    # data_x, data_y, max_length = load_and_preprocess_data(encoder)
    #
    # print("data_x:")
    # print(data_x)
    # print("data_y")
    # print(data_y)
    # print("max_length")
    # print(max_length)
    app = App()
    app.mainloop()

    # Ancient DNA:
    # 'CACTACTGGTGTATCTAATCCTGTTTGCTCCCCACGCTTTCGAGCCTCAGCGTCAGTTACAGACCATAGAGCCGCTTTCGCCACCGGTGTTCCTCCATATTTCTACGCATTTCACCGCTACACATGTACTTCCACTCTCCCCTTCTGCTCTCAAGTTAAACAGTTTCCACAGCTTACTTTGGTTTATCCCCATCCTTTTACTTCATACTTTTCTACCCCCCTGCCCTCTCTTTTCCCCCATCACTTTCCCATTCCCCTTCTCCCCTACCTTTTTCACCTGTCCTCTTCCACTTCTTCTCTC'

    # Modern DNA:
    # 'CCTACGGGCGGCTGCAGTGAGGAATCTTCCACAATGGGCGAAAGCCTGATGGAGCAACGCCGCGTGCAGGATGAAGGCCTTCGGGTTGTAAACTGCTTTTATGATTGAGGAATTTGACAGTAGATCATGAATAAGGATCGGCTAACTACGTGCCAGCAGCCGCGGTCATACGTAGGATCCGAGCGTTATCCGGAGTGACTGGGCGTAAAGAGTTGCGTAGGCGGTTTGTTAAGTGAATAGTGAAATCTGGTGGCTCAACCATAACGGCTATTATTCAAACTGTACAACCCGAAACTGGTAG''
